package com.uncle2000.lib.element

object Constant {
    val PREF_NAME = "lyz_pref.dat"
    val TYPE = "type"
    val PHONE = "phone"
    val ACC = "acc"
    val BO = "bo"
    val LIST = "list"
    val NUM = "num"
    val PSW = "psw"
    val ROLES = "roles"
    val PAGE = "page"
    val ID = "id"
    val CONTENT = "content"
    val TOKEN = "token"
    val IS_FIREST = "isFirst"
    val NAME = "name"
    val ALIAS = "alias"
    val BOOLEAN = "boolean"
    val PATH = "PATH"
    val URL = "url"
    val URI = "uri"
    val FULL_SCREEN = "fullScreen"
}
